apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service-container
          image: backend-service
          imagePullPolicy: IfNotPresent # Always cannot be used with 'latest' local images
          ports:
            - containerPort: 8081
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-service
spec:
  type: ClusterIP # Default
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081