apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-service-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: http-service-container
          image: http-service
          env:
            - name: BACKEND_SERVICE_HOST
              value: backend-service-service
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 30 # Default is 10
            failureThreshold: 1 # Default is 3
            initialDelaySeconds: 4
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 2 # Default is 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: http-service-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080