apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-service-deployment
  labels:
    app: backend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service-container
          image: backend-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: {{ .Values.backend.requests.memory }}
            limits:
              memory: {{ .Values.backend.limits.memory }}
              cpu: {{ .Values.backend.limits.cpu }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service-service
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081